Add image icons
kspalmer/FortuneTeller pull request #2
Opened 2018-02-04 18:11 UTC by kspalmer

All conflicts are resolved.  Want to merge new functionality (add an image appropriate to each fortune) to the master.

2018-02-05 15:48 UTC, acfortier requested changes

2018-02-05 15:48 UTC, acfortier commented on src/imageSupport/SetUpStoneArray.java
> +public class SetUpStoneArray extends ArrayList<ImageIcon> {
Looks pretty good! Can you add Javadoc comments to all classes and functions going forward?

2018-02-05 19:31 UTC, kspalmer commented on src/imageSupport/SetUpStoneArray.java
> +public class SetUpStoneArray extends ArrayList<ImageIcon> {
That sounds like a great idea.  
But, believe it or not, I'm not familiar with how to use Javadoc!  LOL 
So, I'm not sure how to go about doing that.

2018-02-05 19:39 UTC, acfortier commented on src/imageSupport/SetUpStoneArray.java
> +public class SetUpStoneArray extends ArrayList<ImageIcon> {
No worries! Since we're using Eclipse, it actually makes it very easy... If you type /** above the line where a function or class is located, it should automatically generate the format, and then all you need to do is annotate!

We can go over it tonight too, if you'd like

2018-02-05 22:38 UTC, kspalmer commented on src/imageSupport/SetUpStoneArray.java
> +public class SetUpStoneArray extends ArrayList<ImageIcon> {
Thanks to your email, Alex, I have included Javadoc comments in all the classes and for the majority of the methods for the next branch, which will add Astrology!

2018-02-05 23:43 UTC, acfortier commented on src/imageSupport/SetUpStoneArray.java
> +public class SetUpStoneArray extends ArrayList<ImageIcon> {
I don't see them--did you happen to push them yet?

2018-02-05 23:43 UTC, acfortier commented
Also, I don't see unit tests, but maybe @hellokaty37 wants to talk about expectations for testing?

2018-02-06 00:23 UTC, kspalmer commented on src/imageSupport/SetUpStoneArray.java
> +public class SetUpStoneArray extends ArrayList<ImageIcon> {
Alex, your comment was: "Looks pretty good! Can you add Javadoc comments to all classes and functions going forward?"

So, I put them into the code I have for the next branch!  :)  Please don't tell me you need them in this branch, too - I don't have time to do all that work twice!  :(

2018-02-06 00:26 UTC, kspalmer commented on src/imageSupport/SetUpStoneArray.java
> +public class SetUpStoneArray extends ArrayList<ImageIcon> {
What is needed for unit tests?  I will create a Word doc showing the "pre" application and the "enhanced" application" screen shots if that will help.

2018-02-06 00:27 UTC, acfortier commented on src/imageSupport/SetUpStoneArray.java
> +public class SetUpStoneArray extends ArrayList<ImageIcon> {
Sorry! I guess I wasn't clear--but if that's the case, I'll take your word for it ;)

2018-02-06 00:27 UTC, acfortier approved these changes

2018-02-06 00:31 UTC, kspalmer commented on src/imageSupport/SetUpStoneArray.java
> +public class SetUpStoneArray extends ArrayList<ImageIcon> {
Thanks, Alex.

2018-02-06 00:55 UTC, merged